### ISSUE TITLE
November meetup

### ISSUE THREAD

**Issue by Pallinder** [stockholm-react-js/meetups#1]
# Information
So we plan to have a meetup in November (probably the beginning). 
The target is to get about 100 attendees so we need a place that can hold em all.

## Hosts
- [ ] Can support 100 people?
- [ ] Will supply food / drinks?

## Speakers
I have a few leads on the speakers but we should target to have 2 quite popular talks to drive people to come and perhaps a lightning talk or two. 

It would also be a great place to announce the changes we are working on for the community, to really get the buzz going.

**Comment by Pallinder** [comment]
## Hosts
We are looking at a couple of different places that could function.
@Ephem do you think SVT/SR would be interested in hosting again?

##  Date
Date is set to 15th of Nov barring any speaker issues.

## Speakers
* Framer X 
* Maksim who will speak about react at dice

### Lightning
We are also looking at a few lightning talks

**Comment by Ephem** [comment]
I'm not sure, I'll reach out to one of my old colleagues and see if they are interested. :)

**Comment by Ephem** [comment]
SVT is interested! They will check if they have an available location for the 15th.

**Comment by satansdeer** [comment]
We have a backup location. It's STIM on Hornstul.

**Comment by Pallinder** [comment]
Getting an update from Framer X beginning of next week and they are very excited.

**Comment by satansdeer** [comment]
We have 2 main speakers @satansdeer from DICE and the guy from FramerX. We also have 1 lightning talk from @Bogdan-Lyashenko (and potentially 1 more lightning talk speaker)

**Comment by Ephem** [comment]
I think SVT will want to provide a lightning speaker as well, so let's keep the last (third) spot open for them unless they say otherwise.

**Comment by Ephem** [comment]
SVT is confirmed as a host and have a venue booked for the 15th! (Same venue as last meetup there)

**Comment by Emma-Karin** [comment]
Me and my colleague Vanja will be the project managers for the meetup - we're interns at SVT and don't (yet) know that much about React or JS, but we will know all about the food, venue, schedule etc... Please be in touch if you have any questions or suggestions! :)

**Comment by Ephem** [comment]
[Pull Request](https://github.com/stockholm-react-js/meetups/pull/9) is now open.

**Comment by Ephem** [comment]
Closed by #9, great event, thanks to SVT for excellent hosting, the speakers and everyone who came to the event!
