### ISSUE TITLE
Panel session around ReactConf for November meetup

### ISSUE THREAD

**Issue by Ephem** [stockholm-react-js/meetups#10]
# My idea

I'm thinking about arranging a short panel-event for the [15th of November meetup](https://www.meetup.com/Stockholm-ReactJS-Meetup/events/255801859/) since there are two spots for lightning talks open still. It would include about 3-4 people and a moderator and the aim would be to discuss takeaways from the latest ReactConf on stage, in a relaxed way. My suggestion is that it would be planned to take about 20 minutes, possibly shorter.

Format would be:

* 3-4 people
* A couple of predetermined questions/topics to talk about (not just hooks, but other takeaways from the conference as well, recommendations of what talks to see etc)
* No questions from the audience (reason being lowering stress for participants, and also the fact that none of them will probably have any special knowledge about the things said at the conference, so questions wouldn't make much sense)
* Suggestion for agenda:
  * Short intro by moderator
  * Participants introduce themselves (or moderator does it?)
  * (Possibly a short like 3-minute intro to hooks for those that haven't seen the keynote)
  * Discussion around questions/topics moderated by moderator

# Help needed

* Participants
* Help coming up with questions/topics to discuss (go ahead and post your ideas here in the issue!)
* Refining the format? If you have suggestions how to make this better, I'd love that!

I would be up for either moderating the panel or participating (but don't have to do either), but more participants would be needed.

Participants should be as diverse as possible, I would love to see both juniors and seniors from different backgrounds and different companies give their take on the conference. I guess the only requirements would be that you have seen the keynote videos as well as a couple of more videos from the conference and would be willing to talk about your impressions of them. (If you were actually at the conference, that would be fantastic of course!).

If this sounds interesting, please leave a comment!

**Comment by Pallinder** [comment]
Love this.

**Comment by FilipStenbeck** [comment]
Very good idea.

**Comment by Ephem** [comment]
Glad to hear! Two participants are now booked, both the main speakers (Artem & Maksim) were interested in participating which seems like a great idea.

Still searching for two more participants and/or a moderator.

Will add a comment adding some questions/topics soon.

**Comment by Ephem** [comment]
Just to start us off with a few I had in my head:

* What were your favourite talks from the conference?
* Excluding hooks, what was your biggest takeaway from the conference? What did you learn?
* Concurrent React
  * Are you excited that Suspense has finally landed in the latest release?
  * Is the code your working on day-by-day concurrent-ready? Are you planning to use it at some point?
  * swyx (moderator of React sub-reddit) tweated "I think Suspense is a big deal for library authors, but Time Slicing is a bigger deal for app authors.", what are your thoughts on this? Have Time Slicing been under-hyped compared to Suspense?
  * What are your thoughts on the future around concurrent React? Will it help with the usecase you are working on at the moment?
* Hooks
  * Temperature check - All participants make a thumbs up, thumbs down or thumbs side on hooks
  * Each participant gets to explain why
  * Have any of you experimented with them? What were your thoughts from that?
  * Despite Dan saying during the keynote that this just is a proposal and to not refactor all your class components, there has been jokes in the community that that was what was going to happen everywhere right after the conference. Did you? Are you now class-free?
  * Joking aside, if you wrote a new project after hooks have been released, would you write any more class-based components?
  * If you plan to introduce hooks at your company or in your projects, how are you planning or would you plan to do it? Only for new components? Gradually refactor old? Go all in?

None of this has been filtered or refined really so please comment, I just wrote down all the things that was spinning around in my head. :)

**Comment by asci** [comment]
Awesome idea!

**Comment by Ephem** [comment]
I've asked around a bit but haven't found any other participants yet, so this still might or might not happen. :) Might even be decided on the day of the event.

**Comment by Ephem** [comment]
Panel never happened because we found no more interested participants on such short notice. Next meetup will probably be too far after ReactConf for this to make any sense so closing issue.

That said, I do like the idea of trying out a panel-format so might try to pull off something similar in the future with some more preparation and time. :)
