### ISSUE TITLE
A talk on moving away from static site generators

### ISSUE THREAD

**Issue by palmenhq** [stockholm-react-js/meetups#15]
# Introduction
Here at @HedvigInsurance we’ve moved away from using a static site generator (gatsby) in favor of dynamic page rendering for SSRed web apps. **If there’s an interest** I could share the reasoning and learnings from it, as a contrast to the excellent talk Richard held on moving towards them :)

# My idea
We have two major web apps of interest for this talk - our public website and our web onboarding. The former is based on a headless cms called storyblok and TypeScript, and is the project we moved from using a static site generator to being completely dynamic, for good reasons I believe. The latter was built from scratch using SSR, GraphQL and TypeScript and is in a way more interesting because it is more stateful and interacts with the backend more, but has on the other hand never been using Gatsby or similar. However did evaluate gatsby and chose to not use it. It’s just a brief idea so far so if it sounds interesting I can elaborate a bit more and choose a good path :)

# Help needed
Let me know if this would be of interest and I can prep something :)

**Comment by Pallinder** [comment]
Sounds like an excellent idea, would love to hear a talk about this.

**Comment by palmenhq** [comment]
@Pallinder Cool 😄 I would presume you need a proper intro, but apart from that is there anything else you would need?

**Comment by Pallinder** [comment]
@palmenhq nope, not now. I'll open an issue for a September event, would that be a good time for you to hold this talk?

**Comment by palmenhq** [comment]
@pallinder yes absolutely 🙌

**Comment by Pallinder** [comment]
@palmenhq planning for the next event started at #16

**Comment by palmenhq** [comment]
@Pallinder ooh amazing,I’ll get back ASAP with a proper intro text

**Comment by palmenhq** [comment]
Thanks for letting me do this, I'll close this issue now 🙌
