### ISSUE TITLE
October Event

### ISSUE THREAD

**Issue by Pallinder** [stockholm-react-js/meetups#16]
# Introduction
The next react meetup, let's plan it out and get it going!

## Location

Netlight, [Regeringsgatan 25](https://www.google.com/maps/place/Regeringsgatan+25,+111+53+Stockholm/@59.3316174,18.0656284,17z/data=!3m1!4b1!4m5!3m4!1s0x465f9d5e97e5949f:0x4d6daff1ad49e537!8m2!3d59.3316174!4d18.0678171)
It's same building as Gallerian.

## Date

Current "placeholder" date is Oct 17. It's Thursday.

# Todo

- [x] Set Date
- [x] Fix location
- [ ] Get 2-3 speakers

**Comment by Pallinder** [comment]
#15 might be an interesting talk here. @satansdeer you had some leads for a host?

**Comment by satansdeer** [comment]
We have one person on that wanted to give a talk about react. I'll get more info tomorrow.

**Comment by palmenhq** [comment]
If you're interested I'll prep #15 :) 

something like:

> ### Moving away from Gatsby
> Building websites today has become quite complex and a lot of it has to do with all the tooling and hosting solutions that need to be in place. Static site generators, such as Gatsby, have come to fill a void where simplicity is key. So why not use it? At Hedvig, we used to build our website with Gatsby, but we decided to move away from it for several reasons. This is the story about how and why.

**Comment by herrlax** [comment]
Hello 👋 Our speaker (Anna Päärni) will talk about how they scale their in-game UI using react. I'll send her a link to this repo and let her write about it herself :)

**Comment by hebbeh** [comment]
I'll talk about UI scaling in a game that needs to work on multiple platforms, using web technologies. It's mostly learnings from our mistakes and findings and what we have decided to do moving forward! 🏗🙃

**Comment by satansdeer** [comment]
We're going to get t-shirts for our speakers.

Dear speakers @hebbeh @palmenhq tell me your t-shirt sizes.

**Comment by palmenhq** [comment]
@satansdeer Wow nice! I usually have S
Also what is the status on this? :) do we have ideas on when/where? I think possibly we could host something at @HedvigInsurance <strike>but our office would only take so many people (I can look up a rough estimate if this is relevant)</strike> **update:**  aparrently we've had around 70 participants in previous meetups so we could probably host something where we fit

**Comment by satansdeer** [comment]
We are arranging it with Netlight, I'll tell the dates later this week. They have new office, and it's pretty neat.

**Comment by satansdeer** [comment]
Current "placeholder" date is Oct 17, it's thursday in ~3 weeks

**Comment by palmenhq** [comment]
Amazing, I’ll block my calendar

**Comment by satansdeer** [comment]
Next week I want to have interviews with you @palmenhq and @hebbeh.

How do you look at having those + rehearsal during lunch (so you are fresh and full of energy).

I propose 8th next week 12-13pm - interview with Anna.
9th next week 12-13pm - interview with Johan.

Location - Netlight office Regeringsgatan 25

Let me know if the date/times fit you.

**Comment by palmenhq** [comment]
@satansdeer Sure I'm available. What kind of interview is this though? :)

**Comment by satansdeer** [comment]
Informal video interview. I will ask a bunch of fun questions.

**Comment by palmenhq** [comment]
@satansdeer ok perfect 👍

**Comment by Pallinder** [comment]
Since this is now the October event I'll change the title :)

**Comment by satansdeer** [comment]
Guys @palmenhq @hebbeh send me your presentations. I'm gonna go to netlight tommorrow to check the equipment.

I want to try streaming the event. So if you don't mind i would ask you to use windows machine during the event (if your's won't work with my streaming equipment.)

**Comment by palmenhq** [comment]
@satansdeer sure, i assume you want it in a pptx format?

**Comment by satansdeer** [comment]
yes, it works

**Comment by satansdeer** [comment]
Talk excerpt by Anna:

How to develop scalable game UI.

Using web technologies for UI scaling in a game, that needs to work on multiple platforms. The requirement for pixel perfection and a custom renderer means unique challenges, and a different approach to dynamic web design then I was used to.  A lot of learnings from our mistakes and findings, and what we have decided to do moving forward!
