### ISSUE TITLE
Meetup @ Hedvig

### ISSUE THREAD

**Issue by palmenhq** [stockholm-react-js/meetups#25]
# My idea
We'd love to sponsor or host an event here at @HedvigInsurance. We can provide (probably) a speaker (if needed), (definitely) a cozy venue at our office for around 50-60 people and (for sure) pizzas/wraps/whatever + beer/soda/whatever.

# Help needed
Set a date, maybe late January or early February, one or two speakers and an event @ meetup.com.

**Comment by Pallinder** [comment]
Cool! Let's make this happen then. We would need to find some more speakers, what would your talk be about?

**Comment by palmenhq** [comment]
We just had an interesting project where we built an interactive chat onboarding using a tool made for non-linear storytelling. I think @sampettersson could boil this down to a very interesting talk

**Comment by dafnarosenblum** [comment]
Hi @palmenhq! I've join David in organising Stockholm ReactJS, and will be your contact person for this meet-up. Quick update: I'm looking for additional speaker, and we might do one meet-up before the one with you, so we aim to host the one with you around the end of Feb / beginning of March. Will that work for you?

**Comment by palmenhq** [comment]
Hey @dafnarosenblum, amaze! Yes that'd be perfect. Let me know if we can help in any other way :)

**Comment by dafnarosenblum** [comment]
Hi @palmenhq, can you please check which day in week 9 except Friday can work for you? And do you have another speaker that would like to talk at this event? Thanks!

**Comment by palmenhq** [comment]
@dafnarosenblum hey, amaze! Would Thursday, Feb 27th, be ok? I've just sent out a notification to the office just to double check so we don't have any other activities, but it should be fine afai can see - or I'll get back with another date ASAP.

I'll reach out for another speaker - but if we really can't find another speaker, and are OK with two speakers from Hedvig, I could do a talk on how to tackle a legacy code base - if that could be a topic of interest :)

**Comment by dafnarosenblum** [comment]
Hi @palmenhq, the date is great and your talk sounds great. I'll create a meet-up event soon, can you send me the full names of the speakers and a title and 2-3 sentences about the talks?

**Comment by palmenhq** [comment]
Amaze!
1.
**How we used non-linear storytelling to create a scalable user onboarding** by Sam Pettersson (@sampettersson)
Insurance is complicated, to onboard a customer we need to ask various questions that in turn might lead to more questions. This lead us on a path to build a scalable web and app-onboarding solution inspired by non-linear storytelling.

2.
**Legacy coding without going insane** by Johan Palmfjord (@palmenhq )
Browsing up and down files of crappy code that someone who doesn’t work here anymore wrote a long time ago, that turned into legacy, sucks. But it’s something that most of us just have to live with. However we can choose to tackle it in different ways. This talk will present some strategies for how to (hopefully) not break things - or worse - lose your mind completely.

**Comment by Pallinder** [comment]
Awesome! Looking forward to this one.

**Comment by Pallinder** [comment]
Closing this as it was done :)
