### ISSUE TITLE
Come up with a way to separate the repos

### ISSUE THREAD

**Issue by Pallinder** [stockholm-react-js/meetups#5]
Im thinking this repo should *only* be for meetups. Meta discussion etc
are perhaps handled elsewhere?

**Comment by Pallinder** [comment]
Just realised that github has projects on a organisation level as well. Can be used to handle tasks for the org as a whole, just a bit worried that it will be difficult to find things and get a good overview.

**Comment by Ephem** [comment]
Hmm, I am a bit worried of scattering things too much as well. On the other hand, keeping everything in one repo could also get a bit unfocused..

Maybe separate into three?

* Website
* Meetups(/and Events) - Main public-facing one
* Governance - Planning, meta, admin, meeting-notes etc

I guess the important thing is to make it really clear, at the top of the Readmes for example, what goes where.

**Comment by Pallinder** [comment]
I like that, governance can keep all discussion about why and how while the meetups are straight to the point. Should make it more clear.

To try and make things as clear as possible we could add the links on the website landing page.

**Comment by Pallinder** [comment]
Perhaps you could prepare the Governance repo? And I'll close this.

**Comment by Ephem** [comment]
That sounds great to me. This would mean that most people interested in the community only needs to visit one repo.

The ones that need to visit more then the core "meetup" one are the ones more deeply involved and they shouldn't have any problems navigating between them.

I'll set it up asap!
